 theme: jekyll-theme-hacker
title: "Bitcoin Merchant Starter Kit"
description: "This is a starter kit for any aspiring bitcoin merchants"
author: "@nolim1t"
exclude: ["scripts/*.sh", "socialmedia.sh", "canary.sh", "generate.sh", "README.md", ".git"]
